OrdererOrgs:
  - Name: Orderer
    Domain: iotblockchain.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.iotblockchain.com
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.iotblockchain.com
    Template:
      Count: 3
    Users:
      Count: 1
