version: '2'

services:
  ca.org2.iotblockchain.com:
    image: hyperledger/fabric-ca:1.2.1
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.iotblockchain.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.iotblockchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/{ORG2-CA-KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.iotblockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.iotblockchain.com

  peer0.org2.iotblockchain.com:
    container_name: peer0.org2.iotblockchain.com
    image: hyperledger/fabric-peer:1.2.1
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.iotblockchain.com
      - CORE_PEER_ADDRESS=peer0.org2.iotblockchain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start 
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org2.iotblockchain.com/peers/peer0.org2.iotblockchain.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org2.iotblockchain.com/users:/etc/hyperledger/msp/users
    depends_on:
      - couchdb3
  
  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:0.4.10
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    ports:
      - 8984:5984
    environment:
      DB_URL: http://localhost:8984/member_db

  peer1.org2.iotblockchain.com:
    container_name: peer1.org2.iotblockchain.com
    image: hyperledger/fabric-peer:1.2.1
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.iotblockchain.com
      - CORE_PEER_ADDRESS=peer1.org2.iotblockchain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 11051:7051
      - 11053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org2.iotblockchain.com/peers/peer1.org2.iotblockchain.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org2.iotblockchain.com/users:/etc/hyperledger/msp/users
    depends_on:
      - couchdb4
  
  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb:0.4.10
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    ports:
      - 9984:5984
    environment:
      DB_URL: http://localhost:9984/member_db

  peer2.org2.iotblockchain.com:
    container_name: peer2.org2.iotblockchain.com
    image: hyperledger/fabric-peer:1.2.1
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2.org2.iotblockchain.com
      - CORE_PEER_ADDRESS=peer2.org2.iotblockchain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 12051:7051
      - 12053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org2.iotblockchain.com/peers/peer2.org2.iotblockchain.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org2.iotblockchain.com/users:/etc/hyperledger/msp/users
    depends_on:
      - couchdb5
  
  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb:0.4.10
    logging:
      driver: "json-file"
        options:
           max-file: "5"
           max-size: 10m
    ports:
      - 10984:5984
    environment:
      DB_URL: http://localhost:10984/member_db